# Generated by Django 5.2.12 on 2026-03-20 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Superhero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('intelligence', models.IntegerField(default=0)),
                ('strength', models.IntegerField(default=0)),
                ('speed', models.IntegerField(default=0)),
                ('durability', models.IntegerField(default=0)),
                ('power', models.IntegerField(default=0)),
                ('combat', models.IntegerField(default=0)),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('alter_egos', models.CharField(blank=True, max_length=255)),
                ('aliases', models.JSONField(blank=True, default=list)),
                ('place_of_birth', models.CharField(blank=True, max_length=255)),
                ('first_appearance', models.CharField(blank=True, max_length=255)),
                ('publisher', models.CharField(blank=True, max_length=255)),
                ('alignment', models.CharField(choices=[('good', 'Hero'), ('bad', 'Villain'), ('neutral', 'Neutral'), ('unknown', 'Unknown')], max_length=20)),
                ('gender', models.CharField(blank=True, max_length=50)),
                ('race', models.CharField(blank=True, max_length=100)),
                ('height_cm', models.FloatField(blank=True, null=True)),
                ('weight_kg', models.FloatField(blank=True, null=True)),
                ('eye_color', models.CharField(blank=True, max_length=50)),
                ('hair_color', models.CharField(blank=True, max_length=50)),
                ('occupation', models.CharField(blank=True, max_length=255)),
                ('base', models.CharField(blank=True, max_length=255)),
                ('image_url', models.URLField(blank=True)),
                ('is_edited', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
