# Generated by Django 5.2.12 on 2026-03-20 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('superheroes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('superhero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourited_by', to='superheroes.superhero')),
            ],
        ),
    ]
